server:
  port: 8088
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/quxg?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
instance:
  prefer-ip-address: true
  ip-address: 127.0.0.1

mybatis:
  type-aliases-package: qu.com.user.utils
